### ISSUE TITLE
Could add appendix to cover more advanced topics

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#26]
The ggplot and possibly interfacing with Excel training are going to have an appendix for more advanced material/FAQs - could be something to think about for more advanced topics.

**Comment by chloepugh** [comment]
We have the beginnings of an appendix that covers a bit more on NSE and the janitor package, but could be added to.

Also noticed that a link to the Appendix needs adding to the contents in the README.
