### ISSUE TITLE
R has an "extract function" option which could be worth trying out

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#34]
> EXTRACT FUNCTION
> RStudio comes with a tool that can help you build functions. To use it, highlight the lines of code in your R script that you want to turn into a function. Then click Code > Extract Function in the menu bar. RStudio will ask you for a function name to use and then wrap you code in a function call. It will scan the code for undefined variables and use these as arguments.
> 
> You may want to double-check RStudio’s work. It assumes that your code is correct, so if it does something surprising, you may have a problem in your code.

Source - https://www.oreilly.com/library/view/hands-on-programming-with/9781449359089/ch01.html

**Comment by markrangan** [comment]
I had a look at the extract function and had a play around with it. Would be nice to include it in the Writing Functions session. Saves time when creating functions. 

If you write "a + b", you can highlight it then click on "Extract Function", which can immediately create the add function. We can talk about "Extract Function" at the part of the course that covers basic functions.

**Comment by katharinebreeze** [comment]
@markrangan I think I'm leaning towards not including it as we already have too much content rather than too little. I've never used it, though I do think it could be a good way to help people avoid using undefined variables in their functions.

**Comment by chloepugh** [comment]
@markrangan this might be something to add to the appendix, rather than the main course. I'm not sure how well it would handle more complicated pieces of code (e.g. where non-standard evaluation is involved), but I haven't tried it myself yet.
