### ISSUE TITLE
Remove_indices_from_columns() in exercise 5 to be changed

### ISSUE THREAD

**Issue by georginaeaton** [moj-analytical-services/writing_functions_in_r#48]
Currently the question for exercise 5 (slide 44 in slides but also in the read_me on repo) asks to write a wrapper function to apply generalise_names(), remove_indices_from_columns(), and clean_not_known() but remove_indices_from_columns() is not used in the example code. This should be changed to remove_numbering() (which is used in the example_code.R script and in the solutions to the exercise).

**Comment by chloepugh** [comment]
Addressed in PR #47
