### ISSUE TITLE
Cover binary/relational operators (i.e. > < == !=)

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#50]
Pulling this out as a separate issue from #42.

We use these quite a lot for if else & case when statements - think it'd be useful including a table of them or having a hint to explain how to bring up the help page.

**Comment by chloepugh** [comment]
I've made a table of these for the R Intro extension, which could potentially be copied into this course: https://github.com/moj-analytical-services/intro_r_training_extension/blob/chloe_add_cond_stats/rmd_files/appendix.Rmd

(I had a nightmare trying to get the "|" symbol into a markdown table that was constructed out of | symbols, but found a work-around eventually!)

**Comment by markrangan** [comment]
@katharinebreeze @chloepugh This table could be mentioned in the slide for "Example 3: conditional statements in functions"
