### ISSUE TITLE
Include name/email address of someone to contact regarding feedback/issues/questions

### ISSUE THREAD

**Issue by ms130** [moj-analytical-services/writing_functions_in_r#53]

**Comment by katharinebreeze** [comment]
That's a good point, especially now we have the recordings & are starting to encourage people more to go through the material on their own.

In terms of questions/support - I may be being over-cautious but I'm not sure we want a named contact in case there are a lot of questions/requests for help! My preference would be to encourage people to ask questions on slack, probably on one of the existing `#r` or `#intro_r` channels.

In terms of feedback & issues - we could add a note directing people to Airtable (for general feedback) and to raising an issue here for content issues/suggestions.

If we really want a named contact we could setup an R training mailbox but there would be issues here around who monitored this.

Presumably this is an issue which affects other courses as well so it could be good to co-ordinate.

What do you think?

**Comment by ms130** [comment]
Regarding R questions/support, I agree that the slack channels are probably the best avenue for people to get help and guidance. 

I had in mind more if people have feedback/issues with the course content itself, then it might be useful if they could contact the creators. Especially since near the beginning of the README file it asks people to get in touch if they have any feedback on the content, but without specifying how they should do so. 

I'm not familiar with Airtable, but it sounds like it could be useful to provide general feedback on the content or flag particular issues, if it is monitored by content creators. 

I agree that setting up a R training mailbox might not be necessary, I just noticed that on some of the other courses there was a single named person, and this might be the simplest solution if someone wanted to provide feedback or discuss the content with its creator in more detail. I don't expect that they would receive too many inquires in general.

This is of course all in addition to just logging issues on Github, as I have done here, which I guess works for most issues.

**Comment by markrangan** [comment]
@katharinebreeze @chloepugh I agree with pointing users to Slack to ask for any help on R and to Airtable to provide feedback.
