### ISSUE TITLE
Update non-standard evaluation section/references

### ISSUE THREAD

**Issue by katharinebreeze** [moj-analytical-services/writing_functions_in_r#65]
See issue #42 -

> group_by_at etc functions will be "superseded" in dplyr 1.0.0 (which means slowly phased out) so we probably need to move away from these (see [here](https://www.tidyverse.org/blog/2020/03/dplyr-1-0-0-is-coming-soon/#superseded-functions))

Also see [metaprogramming section](https://adv-r.hadley.nz/metaprogramming.html) of Advanced R (note this goes into a lot of depth, much more than we probably need!).

Code to look at -
https://github.com/moj-analytical-services/writing_functions_in_r#additional-nse-examples

& any of the `*_at()` functions.

**Comment by markrangan** [comment]
@katharinebreeze The following function from slide 53 doesn't work anymore:

> sum_group <- function(df, group_cols, sum_col) {
>   
>   summary <- df %>%
>     dplyr::group_by_at(group_cols) %>%
>     dplyr::summarise_at(sum_col, sum)
>   
>   return(summary)
>   
> }

This should fix it:

> sum_group <- function(df, group_cols, sum_col) {
>   
>   summary <- {{df}} %>%
>     dplyr::group_by(across({{group_cols}})) %>%
>     dplyr::summarise(across({{sum_col}}, sum))
>   
>   return(summary)
>   
> }

Wrapping the group_col and sum_cols arguments with double curly brackets allows the sum_group function to accept that they contain the chosen columns. This is explained in the following link: [https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html](url).

The across function superseded the summarise_at function earlier this year.

**Comment by katharinebreeze** [comment]
Thanks, this looks great! Happy for you to update this & add the link to [Further reading](https://github.com/moj-analytical-services/writing_functions_in_r#further-reading).

As different course participants are likely to have different versions of `dplyr` installed, I think we need to do one of:

1.  Include both versions of the code
2.  Add an additional instruction to the [pre-material](https://github.com/moj-analytical-services/writing_functions_in_r#pre-material) to install `dplyr 1.0.0` or later

My preference is to go for (2) but as I'm sure you're familiar with from Intro R, this is the kind of thing which is likely to cause difficulties for some people! What do you think?

Tagging @chloepugh for awareness!

**Comment by markrangan** [comment]
@katharinebreeze @chloepugh I've started making the changes. For now I'm going with option 2 and have added a line of guidance on how to get the latest dplyr package installed.

**Comment by markrangan** [comment]
Here's the extra point I wrote in the _Writing functions in R: setup_ section:

> Installed the dplyr 1.0.0 or a later version. If you already have an earlier version of dplyr in the User Library (which can be found in the Packages tab), you can delete the package then reinstall it.

**Comment by chloepugh** [comment]
For the next scheduled session I've opted to take an in between route. The following version of the function should be using an up to date method and doesn't require dplyr 1.0. I think it requires rlang 0.4 or later, but most people should have that.
```
sum_group <- function(df, group_cols, sum_col) {

  summary <- df %>%
    dplyr::group_by(.data[[group_cols]]) %>%
    dplyr::summarise(counts = sum(.data[[ sum_col ]]))

  return(summary)
  
}
```

I struggled to get my version of dplyr to update beyond 0.8.5 using conda (using `conda update -c conda-forge r-dplyr`) so I'm not sure how much luck we'd have trying to make sure everyone has an least dplyr 1.0 in the session.

**Comment by katharinebreeze** [comment]
yeah conda doesn't the latest package versions for the current version of RStudio so to install dplyr 1.0.0 you have to use `install.packages()` and possibly also change the snapshot date if that's still a thing. When RStudio is update and/or they introduce venv this should cease to be an issue.

**Comment by chloepugh** [comment]
I'm very much looking forward to the replacement for conda :)
